-- Phase 6 (AC5): scheduled EOD engine batch observability and signal snapshots.
-- The batch runner writes one record per EOD run, links batch-produced
-- recommendations to it, and snapshots each computed technical signal/regime.

CREATE TABLE engine_batch_runs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                  VARCHAR(32)  NOT NULL,
    status                VARCHAR(16)  NOT NULL,
    started_at            TIMESTAMPTZ  NOT NULL,
    completed_at          TIMESTAMPTZ,
    recommendation_count  INTEGER      NOT NULL DEFAULT 0,
    abstention_count      INTEGER      NOT NULL DEFAULT 0,
    signal_snapshot_count INTEGER      NOT NULL DEFAULT 0,
    error_message         TEXT
);

ALTER TABLE recommendations
    ADD COLUMN batch_run_id BIGINT REFERENCES engine_batch_runs(id);

CREATE TABLE signal_snapshots (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_run_id     BIGINT           NOT NULL REFERENCES engine_batch_runs(id),
    symbol           VARCHAR(16)      NOT NULL,
    config_version   INTEGER          NOT NULL REFERENCES engine_config(version),
    as_of_date       DATE             NOT NULL,
    captured_at      TIMESTAMPTZ      NOT NULL,
    chain_as_of      TIMESTAMPTZ      NOT NULL,
    underlying_price DOUBLE PRECISION NOT NULL,
    direction        VARCHAR(16)      NOT NULL,
    conviction       INTEGER          NOT NULL,
    direction_score  DOUBLE PRECISION NOT NULL,
    trend_vote       DOUBLE PRECISION NOT NULL,
    macd_vote        DOUBLE PRECISION NOT NULL,
    rsi_vote         DOUBLE PRECISION NOT NULL,
    ema_fast         DOUBLE PRECISION NOT NULL,
    ema_slow         DOUBLE PRECISION NOT NULL,
    macd_histogram   DOUBLE PRECISION NOT NULL,
    rsi              DOUBLE PRECISION NOT NULL,
    regime           VARCHAR(16)      NOT NULL,
    regime_reason    VARCHAR(512)     NOT NULL,
    current_iv       DOUBLE PRECISION
);

CREATE INDEX idx_engine_batch_runs_started_at
    ON engine_batch_runs (started_at DESC);

CREATE INDEX idx_recommendations_batch_run
    ON recommendations (batch_run_id);

CREATE INDEX idx_signal_snapshots_batch_symbol
    ON signal_snapshots (batch_run_id, symbol);
