-- Phase 8 (AC1): every recommendation gets a forward paper-trade ledger row.
-- The settlement job marks open rows from current option marks and realizes P&L
-- once the recommendation expiry is reached.

CREATE TABLE paper_trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT        NOT NULL UNIQUE REFERENCES recommendations(id),
    symbol            VARCHAR(16)   NOT NULL,
    strategy          VARCHAR(64)   NOT NULL,
    config_version    INTEGER       NOT NULL REFERENCES engine_config(version),
    expiry            DATE          NOT NULL,
    contracts         INTEGER       NOT NULL,
    entry_debit       NUMERIC(19,4) NOT NULL,
    status            VARCHAR(16)   NOT NULL,
    opened_at         TIMESTAMPTZ   NOT NULL,
    last_marked_at    TIMESTAMPTZ,
    mark_debit        NUMERIC(19,4),
    unrealized_pnl    NUMERIC(19,4) NOT NULL DEFAULT 0,
    realized_pnl      NUMERIC(19,4) NOT NULL DEFAULT 0,
    closed_at         TIMESTAMPTZ
);

CREATE INDEX idx_paper_trades_status_opened_at
    ON paper_trades (status, opened_at);

CREATE INDEX idx_paper_trades_config_version
    ON paper_trades (config_version);
