-- Phase 8 (AC3, FR-18, D14): "mark as taken" promotes a recommendation to the
-- real-positions tracker with a manually entered fill price (OQ-8: manual fill
-- entry for accuracy). Separate from paper_trades — this is the true, taken
-- track record. The recommendation itself flips to status = 'TAKEN'.

CREATE TABLE taken_positions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT        NOT NULL UNIQUE REFERENCES recommendations(id),
    symbol            VARCHAR(16)   NOT NULL,
    strategy          VARCHAR(64)   NOT NULL,
    direction         VARCHAR(16)   NOT NULL,
    config_version    INTEGER       NOT NULL REFERENCES engine_config(version),
    expiry            DATE          NOT NULL,
    contracts         INTEGER       NOT NULL,
    fill_price        NUMERIC(19,4) NOT NULL,
    taken_at          TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_taken_positions_symbol ON taken_positions (symbol);
