-- Phase 2 (manual portfolio): stock + option positions (FR-1, FR-2).
-- All I/O flows through the PositionSource seam (ManualPositionSource in V1).
-- No pricing/greeks here — those arrive in Phase 3.

CREATE TABLE positions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(16)    NOT NULL,
    quantity    NUMERIC(19, 4) NOT NULL,
    cost_basis  NUMERIC(19, 4) NOT NULL,
    opened_date DATE           NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE option_positions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    underlying  VARCHAR(16)    NOT NULL,
    option_type VARCHAR(4)     NOT NULL,  -- CALL | PUT
    strike      NUMERIC(19, 4) NOT NULL,
    expiry      DATE           NOT NULL,
    quantity    NUMERIC(19, 4) NOT NULL,
    cost_basis  NUMERIC(19, 4) NOT NULL,
    side        VARCHAR(5)     NOT NULL,  -- LONG | SHORT
    opened_date DATE,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_positions_symbol ON positions (symbol);
CREATE INDEX idx_option_positions_underlying ON option_positions (underlying);
