-- Phase 3 (AC5): daily ATM implied-volatility accumulation (D22, FR-8a).
-- The engine's IV-rank input (Phase 4/5) needs ~1yr of daily ATM IV that nobody
-- has at launch, so a daily job appends one reading per underlying per day,
-- computed in-house via Black-Scholes (never vendor-supplied). One row per
-- (symbol, as_of_date): the job upserts, so a same-day re-run is idempotent.
CREATE TABLE iv_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol           VARCHAR(16)      NOT NULL,
    as_of_date       DATE             NOT NULL,
    atm_iv           DOUBLE PRECISION NOT NULL,  -- annualised, e.g. 0.284531
    underlying_price DOUBLE PRECISION NOT NULL,
    atm_strike       DOUBLE PRECISION NOT NULL,
    expiration       DATE             NOT NULL,  -- the expiry the reading was sampled from
    recorded_at      TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT uq_iv_history_symbol_date UNIQUE (symbol, as_of_date)
);
