-- Phase 4 (AC1/AC2): versioned engine configuration (D21, FR-27–FR-29,
-- strategy-matrix §9.1, docs/config-update-runbook.md §2).
-- Rows are immutable: a tuning change INSERTs a new version and flips
-- is_active — never an in-place edit — so every recommendation's
-- config_version stays resolvable and the paper-trade ledger stays
-- interpretable across retunes. v1 is seeded from the §9 factory defaults
-- (classpath engine/engine-config-defaults.json) at first boot.
CREATE TABLE engine_config (
    version    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config     JSONB       NOT NULL,   -- the entire strategy-matrix §9 object
    is_active  BOOLEAN     NOT NULL DEFAULT false,
    note       TEXT,                   -- why this version exists (runbook requires one)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Exactly one active row, enforced by the database itself (belt-and-braces
-- with the app's transactional flip): a partial unique index over the single
-- value TRUE can hold at most one row.
CREATE UNIQUE INDEX uq_engine_config_single_active
    ON engine_config (is_active)
    WHERE is_active;
