-- Phase 4 (AC3/AC4): persisted recommendations from the first engine slice.
-- V1 starts with one supported structure (Bull Call Debit Spread), but the row
-- shape keeps the key audit fields stable for later matrix cells and ledger work.
CREATE TABLE recommendations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol                VARCHAR(16)    NOT NULL,
    strategy              VARCHAR(64)    NOT NULL,
    direction             VARCHAR(16)    NOT NULL,
    regime                VARCHAR(16)    NOT NULL,
    conviction            INTEGER        NOT NULL,
    status                VARCHAR(16)    NOT NULL DEFAULT 'PAPER',
    config_version        INTEGER        NOT NULL REFERENCES engine_config(version),
    expiry                DATE           NOT NULL,
    long_option_symbol    VARCHAR(64)    NOT NULL,
    long_strike           NUMERIC(19, 4) NOT NULL,
    short_option_symbol   VARCHAR(64)    NOT NULL,
    short_strike          NUMERIC(19, 4) NOT NULL,
    entry_debit           NUMERIC(19, 4) NOT NULL,
    probability_of_profit NUMERIC(19, 6) NOT NULL,
    max_profit            NUMERIC(19, 4) NOT NULL,
    max_loss              NUMERIC(19, 4) NOT NULL,
    risk_reward           NUMERIC(19, 6) NOT NULL,
    score                 NUMERIC(19, 6) NOT NULL,
    rationale             JSONB          NOT NULL,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_recommendations_symbol_created_at
    ON recommendations (symbol, created_at DESC);

CREATE INDEX idx_recommendations_config_version
    ON recommendations (config_version);
